### ISSUE TITLE
Whence AMOMAX?

### ISSUE THREAD

**Issue by sorear** [sorear/riscv-specs#11]
ADD, SUB, OR, AND, XOR, and SWAP are all clearly required by C11 and supported by common CPUs.  It's less clear why we have MAX, MAXU, MIN, and MINU; the specification hints at the "reduction operator" uses, but it's not as explicit as it could be.  I'd like to see a non-normative section laying out why they were added and the expected use cases.

**Comment by kasanovic** [comment]
For parallel reductions - some clarification added to text.
