### ISSUE TITLE
SBI: Feature Testing

### ISSUE THREAD

**Issue by sorear** [sorear/riscv-specs#12]
Currently there is no way for a kernel to make optional use of a new SBI call.  Presumably there should be a new SBI call that returns bitflags for functions you can safely call; this information could also be embedded in the config string at some cost in ergonomics.

**Comment by sorear** [comment]
ECALL-based SBI returns -ENOSYS for unimplemented functions (thus embedding bits of the linux syscall ABI into an OS-neutral ABI, but that's more weird than harmful).

**Comment by neuschaefer** [comment]
As long as the SBI defines its own `ENOSYS` which may or may not be the same as Linux's `ENOSYS`, I see no problem there. Blindly borrowing it from Linux might not be a good idea.

**Comment by sorear** [comment]
Currently it's [coming from newlib](https://github.com/riscv/riscv-pk/blob/6667bc4c42fd9968527644e32841757234285efd/machine/mtrap.c#L6).

Added riscv/riscv-isa-manual#38 to track that bit.
