### ISSUE TITLE
Paolo Bonzini wants H-mode removed

### ISSUE THREAD

**Issue by sorear** [sorear/riscv-specs#15]
Thread: https://groups.google.com/a/groups.riscv.org/d/msg/isa-dev/SfEDPLU0NU4/WpAE_A4OBQAJ

Summary: H-mode as a distinct concept was explored by ARMv8 and found to be significantly inferior to S-mode virtualization extensions as found on s390 and x86, especially for the needs of type-2 hypervisors.

**Comment by kasanovic** [comment]
This was done, though space is still reserved.
