### ISSUE TITLE
Strongly consider hosting specs on GitHub with an issue tracker

### ISSUE THREAD

**Issue by sorear** [sorear/riscv-specs#17]
The Foundation has proposed to start publishing the specs on arXiv.  However, arXiv has no issue tracking and limited change tracking, so IMO a code host like GitHub is better suited for the collaborative development of a document which requires public review for all changes.  (There are of course alternatives, but the Foundation is already using GitHub.)

An option would be to adopt this repo officially and put the specs in it.  (If that happens I'd have to stop using it as my private wishlist.)

**Comment by kasanovic** [comment]
Done!  Would be great to move the unresolved issues here over to the spec's GitHub tracker.

**Comment by sorear** [comment]
@kasanovic Thanks for reminding me.  I'll clean this up now.
