### ISSUE TITLE
Linux boot protocol needs to be defined

### ISSUE THREAD

**Issue by sorear** [sorear/riscv-specs#20]
Previously: #19, #16, #8, #1 

The current "boot protocol" used by BBL and Linux is too minimal for my use cases.

* No data can be passed to the kernel (no initramfs pointer, append string, etc; especially for QEMU we would like to be able to pass arguments to the kernel!)
* There's no reserved arguments so we _can't_ add parameter passing, without resorting to x86-like tricks where the boot loader passes arguments by patching known offsets in the kernel
* Direct maps are set up by BBL, artificially limiting memory to 2G

What I'd like to see, largely following AArch64:

* $a0 points at a binary device tree in main memory (which will often be constructed by the boot loader, so representing this textually is counterproductive)
* Paging is disabled, or at least the kernel itself, the device tree, and a healthy amount of allocatible memory is identity-mapped; having to cope with address translation prior to the point when the kernel starts managing its own paging is a pain
* All other boot parameters, including the memory map, are pulled from the device tree

**Comment by eternaleye** [comment]
One thing to consider: Should we really be defining a Linux boot protocol? Or should we define a generic boot protocol, and ensure it provides everything needed for a Linux boot protocol to be built on top?

I'd argue that the latter is a better option - in particular, I'd strongly suggest _specifying_ a simple, idiomatic ELF-based boot protocol, which passes the textual device tree (as that seems to be what the spec folks are moving towards), a command line, and nothing else.

Linux, then, can trivially have a "boot stub" to adapt this to whatever boot protocol works best for it, the same as is done on EFI. In addition, by using a well-specified format, it will be easier for other OSes to make use of this (such as seL4).

The initial version would likely use kernels with a built-in initramfs image; a later extension could easily add an auxval for the initramfs (or pass it in the device tree).

Similarly a later _optimization_ could define an additional auxval type for the binary FDT, etc, to improve the _efficiency_ of the Linux boot process. This is made possible by ELF being a format with clear extension points, unlike the above.

**Comment by sorear** [comment]
The generic boot protocol is out of scope for this ticket.  This ticket is to define the Linux boot protocol; if we can make it work out of the box for other kernels, great, but any large changes should really be cleared with somebody from https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/MAINTAINERS .

Textual device tree is a bad idea for Linux because parsing it in the early boot environment would require a completely separate set of functions, and because (previous point) other architectures use binary.

Once we have a good idea of what the Linux protocol should look like (which requires opinions from kernel devs, _not_ people like you or me), we can start to think about what a kernel-independent protocol might look like.

**Comment by sorear** [comment]
The boot protocol is now where I want it, but I'm going to move the goalposts and leave this ticket open until it is documented.

**Comment by sorear** [comment]
This is adequately covered by riscv/riscv-isa-manual#38
