### ISSUE TITLE
sbi_hart_id versus the boot protocol

### ISSUE THREAD

**Issue by sorear** [sorear/riscv-specs#27]
Ron Minnich points out that sbi_hart_id through an upcall is a bit weird: https://groups.google.com/a/groups.riscv.org/d/topic/isa-dev/frrGFW95j1s/discussion

The simplest proposal at this point is to kill the SBI call and just provide the hart id in the bringup code, requiring the supervisor to track it in sscratch/tp if it cares.

**Comment by neuschaefer** [comment]
This seems to require that the firmware brings up all harts. Such a requirement should be made explicit once the boot protocol is specified. How will a hart find its hartid when it's started at runtime?

**Comment by sorear** [comment]
priv-1.10 passes hart id in `a0` and device tree pointer in `a1`
