### ISSUE TITLE
Memory model is weaker than we want

### ISSUE THREAD

**Issue by sorear** [sorear/riscv-specs#4]
It's currently roughly Alpha, which nobody expects back, and has "interesting" implications for page zeroing on Linux and BSD kernels (NT should work fine because it still does zeroidle).

Foundation has [expressed intent](https://groups.google.com/a/groups.riscv.org/d/msg/isa-dev/Va2bE2kf7uw/SHG5Vj_vAQAJ) to strengthen it to roughly ARM/PowerPC level.

**Comment by kasanovic** [comment]
Foundation memory model task group has been spun up.
